import localFont from "next/font/local";
import "./globals.scss";
import { motion } from "framer-motion";
import Footer from "./footer/footer.page";


import SectionHomeInfo from "./sectionHomeInfo/SectionHomeInfo.page";

import Loader from "./components/loading/Loading.page";

import AnimText from "./components/loading/anim_text/AnimText.page";
import SliderSite from "./sliderSite/SliderSite.page";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Person site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <AnimText> */}
        {/* <Loader> */}
          <div>
            <div className="section">
           
              {children}
            </div>

            <div className="section">
              <SectionHomeInfo />
            </div>
            <div className="section">
            <SliderSite/>
            
            </div>

           
            <div className="section">
              <Footer />
            </div>
          </div>
        {/* </Loader> */}
        {/* </AnimText> */}
       
      </body>
    </html>
  );
}
