import localFont from "next/font/local";
import "./globals.scss";
// import { motion } from "framer-motion";
import AnimText from "./components/loading/anim_text/AnimText.page.jsx";

const geistSans = localFont({
  src: "./fonts/Comfortaa-VariableFont_wght.ttf",
  variable: "--font-title",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Person site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <AnimText>  */}
         {/* <Loader>  */}
       {children}
         {/* </Loader>  */}
         {/* </AnimText>   */}
      </body>
    </html>
  );
}
